parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Subscriber\BottleSubscriber:
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  App\Subscriber\UserSubscriber:
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  App\Subscriber\WineSubscriber:
    tags:
      - { name: doctrine.event_subscriber, connection: default }
